name: .NET

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Dii_TheaterManagement_Bff.sln
    - name: Build
      run: dotnet build Dii_TheaterManagement_Bff.sln --no-restore
    - name: Test
      run: |
         dotnet test test/Dii_TheaterManagement_Bff.Acceptance.Tests/Dii_TheaterManagement_Bff.Acceptance.Tests.csproj --no-build --verbosity normal
      shell: bash
    - name: GenerateSpecFlowLivingDoc
      run: |
        echo "Generating Acceptance Tests LivingDoc"
        ACCEPTANCE_TEST_PATH=$(find . -type d -iname "*.Acceptance.Tests")
        echo "Full Path: " $ACCEPTANCE_TEST_PATH
        ACCEPTANCE_TEST_FOLDER=$(basename $ACCEPTANCE_TEST_PATH)
        echo "Folder Name: " $ACCEPTANCE_TEST_FOLDER
        ACCEPTANCE_TEST_DLL=$(find $ACCEPTANCE_TEST_PATH -type f -iname "${ACCEPTANCE_TEST_FOLDER}.dll" -ipath "*/bin/*" -not -ipath "*/ref/*")
        echo "Test Assembly: " $ACCEPTANCE_TEST_DLL
        ACCEPTANCE_TEST_JSON=$(find $ACCEPTANCE_TEST_PATH -type f -iname "TestExecution.json" -ipath "*/bin/*" -not -ipath "*/ref/*")
        echo "Execution Json: " $ACCEPTANCE_TEST_JSON
        livingdoc test-assembly $ACCEPTANCE_TEST_DLL -t $ACCEPTANCE_TEST_JSON -o livingdoc.html 
      shell: bash
    - name: 'Publish Specflow Test Results'
      uses: actions/upload-artifact@v2
      with:
        name: 'Specflow Test Results'
        path: LivingDoc.html
